// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Profile struct {
	UserID   string  `json:"userID"`
	Nickname *string `json:"nickname,omitempty"`
}

func (Profile) IsEntity() {}

type Query struct {
}
