version: "3"

includes:
  frontend:
    dir: ./frontend
    taskfile: ./frontend/Taskfile.yml
  backend:
    dir: ./backend
    taskfile: ./backend/Taskfile.yml

tasks:
  default:
    # Эта задача выполняется по умолчанию при вызове 'task' без аргументов.
    # Она скрыта из списка, так как у нее нет 'desc'.
    cmds:
      - task --list
      - echo "task <name> --summary"
    silent: true

  docker-up:
    desc: "Run local docker compose stack"
    cmds:
      - task backend:gateway-compose
      - docker compose up -d --build

  docker-down:
    desc: "Stop local docker compose stack"
    cmd: docker compose down

  kill-port:
    desc: "Kill specific port"
    summary: |
      Kill specific port.

      EXAMPLE:
        task kill-port -- 7171
    cmds:
      - lsof -ti:{{.CLI_ARGS}} | xargs kill -9
