// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: backend/profile/pkg/grpc/profile.proto

package profilepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_backend_profile_pkg_grpc_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SetNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNicknameRequest) Reset() {
	*x = SetNicknameRequest{}
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNicknameRequest) ProtoMessage() {}

func (x *SetNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNicknameRequest.ProtoReflect.Descriptor instead.
func (*SetNicknameRequest) Descriptor() ([]byte, []int) {
	return file_backend_profile_pkg_grpc_profile_proto_rawDescGZIP(), []int{1}
}

func (x *SetNicknameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_profile_pkg_grpc_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_backend_profile_pkg_grpc_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_backend_profile_pkg_grpc_profile_proto protoreflect.FileDescriptor

const file_backend_profile_pkg_grpc_profile_proto_rawDesc = "" +
	"\n" +
	"&backend/profile/pkg/grpc/profile.proto\x12\n" +
	"profile.v1\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x12SetNicknameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"F\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname2\xa6\x01\n" +
	"\x0eProfileService\x12H\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x1b.profile.v1.ProfileResponse\x12J\n" +
	"\vSetNickname\x12\x1e.profile.v1.SetNicknameRequest\x1a\x1b.profile.v1.ProfileResponseBDZBgithub.com/pure-golang/monorepo/backend/profile/pkg/grpc;profilepbb\x06proto3"

var (
	file_backend_profile_pkg_grpc_profile_proto_rawDescOnce sync.Once
	file_backend_profile_pkg_grpc_profile_proto_rawDescData []byte
)

func file_backend_profile_pkg_grpc_profile_proto_rawDescGZIP() []byte {
	file_backend_profile_pkg_grpc_profile_proto_rawDescOnce.Do(func() {
		file_backend_profile_pkg_grpc_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_profile_pkg_grpc_profile_proto_rawDesc), len(file_backend_profile_pkg_grpc_profile_proto_rawDesc)))
	})
	return file_backend_profile_pkg_grpc_profile_proto_rawDescData
}

var file_backend_profile_pkg_grpc_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backend_profile_pkg_grpc_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: profile.v1.GetProfileRequest
	(*SetNicknameRequest)(nil), // 1: profile.v1.SetNicknameRequest
	(*ProfileResponse)(nil),    // 2: profile.v1.ProfileResponse
}
var file_backend_profile_pkg_grpc_profile_proto_depIdxs = []int32{
	0, // 0: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	1, // 1: profile.v1.ProfileService.SetNickname:input_type -> profile.v1.SetNicknameRequest
	2, // 2: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.ProfileResponse
	2, // 3: profile.v1.ProfileService.SetNickname:output_type -> profile.v1.ProfileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_profile_pkg_grpc_profile_proto_init() }
func file_backend_profile_pkg_grpc_profile_proto_init() {
	if File_backend_profile_pkg_grpc_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_profile_pkg_grpc_profile_proto_rawDesc), len(file_backend_profile_pkg_grpc_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_profile_pkg_grpc_profile_proto_goTypes,
		DependencyIndexes: file_backend_profile_pkg_grpc_profile_proto_depIdxs,
		MessageInfos:      file_backend_profile_pkg_grpc_profile_proto_msgTypes,
	}.Build()
	File_backend_profile_pkg_grpc_profile_proto = out.File
	file_backend_profile_pkg_grpc_profile_proto_goTypes = nil
	file_backend_profile_pkg_grpc_profile_proto_depIdxs = nil
}
