package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	graphql1 "github.com/pure-golang/monorepo/backend/auth/internal/transport/http/graphql"
	"github.com/pure-golang/monorepo/backend/auth/internal/transport/http/graphql/model"
)

// RequestEmailCode is the resolver for the requestEmailCode field.
func (r *mutationResolver) RequestEmailCode(ctx context.Context, email string) (*model.RequestEmailCodePayload, error) {
	result, err := r.authService.RequestCode(ctx, email)
	if err != nil {
		return nil, err
	}
	return &model.RequestEmailCodePayload{
		Accepted:          result.Accepted,
		RetryAfterSeconds: result.RetryAfterSeconds,
		NextAllowedAt:     &result.NextAllowedAt,
	}, nil
}

// LoginWithEmailCode is the resolver for the loginWithEmailCode field.
func (r *mutationResolver) LoginWithEmailCode(ctx context.Context, email string, code string) (*model.LoginPayload, error) {
	session, err := r.authService.LoginByCode(ctx, email, code)
	if err != nil {
		return nil, err
	}
	return &model.LoginPayload{
		Token:  session.Token,
		UserID: session.UserID,
		Email:  session.Email,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, allDevices *bool) (*model.LogoutPayload, error) {
	token := authTokenFromContext(ctx)
	var err error
	if allDevices != nil && *allDevices {
		err = r.authService.LogoutEverywhere(ctx, token)
	} else {
		err = r.authService.Logout(ctx, token)
	}
	if err != nil {
		return nil, err
	}
	return &model.LogoutPayload{Revoked: true}, nil
}

// AuthStatus is the resolver for the authStatus field.
func (r *queryResolver) AuthStatus(ctx context.Context) (string, error) {
	return "ok", nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
