version: 1
subgraphs:
  - name: auth
    routing_url: http://localhost:8081/graphql
    schema:
      file: ../auth/internal/transport/http/graphql/schema.graphqls
  - name: profile
    routing_url: http://localhost:8082/graphql
    schema:
      file: ../profile/internal/transport/http/graphql/schema.graphqls

