package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	graphql1 "github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql"
	"github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql/model"
)

// FindProfileByUserID is the resolver for the findProfileByUserID field.
func (r *entityResolver) FindProfileByUserID(ctx context.Context, userID string) (*model.Profile, error) {
	profile, err := r.profileService.GetByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return profileToModel(profile), nil
}

// Entity returns graphql1.EntityResolver implementation.
func (r *Resolver) Entity() graphql1.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
