package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/pure-golang/monorepo/backend/profile/internal/domain"
	graphql1 "github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql"
	"github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql/model"
)

// SetNickname is the resolver for the setNickname field.
func (r *mutationResolver) SetNickname(ctx context.Context, nickname string) (*model.Profile, error) {
	user, err := r.authService.ValidateToken(ctx, authTokenFromContext(ctx))
	if err != nil {
		return nil, err
	}
	profile, err := r.profileService.SetNickname(ctx, user.UserID, nickname)
	if err != nil {
		return nil, err
	}
	return profileToModel(profile), nil
}

// ProfileStatus is the resolver for the profileStatus field.
func (r *queryResolver) ProfileStatus(ctx context.Context) (string, error) {
	return "ok", nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	user, err := r.authService.ValidateToken(ctx, authTokenFromContext(ctx))
	if err != nil {
		return nil, err
	}
	profile, err := r.profileService.GetByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}
	return profileToModel(profile), nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func profileToModel(profile *domain.Profile) *model.Profile {
	if profile == nil {
		return nil
	}
	return &model.Profile{
		UserID:   profile.UserID,
		Nickname: profile.Nickname,
	}
}
