package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"

	"github.com/pure-golang/monorepo/backend/profile/internal/domain"
	graphql1 "github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql"
	"github.com/pure-golang/monorepo/backend/profile/internal/transport/http/graphql/model"
)

// SetNickname is the resolver for the setNickname field.
func (r *mutationResolver) SetNickname(ctx context.Context, nickname string) (*model.Profile, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.profileService.SetNickname(ctx, user.UserID, nickname)
	if err != nil {
		return nil, err
	}
	return profileToModel(profile), nil
}

// ProfileStatus is the resolver for the profileStatus field.
func (r *queryResolver) ProfileStatus(ctx context.Context) (string, error) {
	return "ok", nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}
	profile, err := r.profileService.GetByUserID(ctx, user.UserID)
	if err != nil {
		return nil, err
	}
	return profileToModel(profile), nil
}

// NicknameAvailability is the resolver for the nicknameAvailability field.
func (r *queryResolver) NicknameAvailability(ctx context.Context, nickname string) (*model.NicknameAvailability, error) {
	normalizedNickname := strings.TrimSpace(nickname)
	if userID := userIDFromContext(ctx); userID != "" {
		profile, err := r.profileService.GetByUserID(ctx, userID)
		if err != nil && !errors.Is(err, domain.ErrProfileNotFound) {
			return nil, err
		}
		if profile != nil && profile.Nickname != nil && *profile.Nickname == normalizedNickname {
			return &model.NicknameAvailability{Nickname: normalizedNickname, Available: true}, nil
		}
	}
	available, err := r.profileService.IsNicknameAvailable(ctx, normalizedNickname)
	if err != nil {
		return nil, err
	}
	return &model.NicknameAvailability{Nickname: normalizedNickname, Available: available}, nil
}

func (r *Resolver) currentUser(ctx context.Context) (*domain.User, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, domain.ErrUnauthenticated
	}
	return r.userService.GetUser(ctx, userID)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
