// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user/pkg/grpc/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateUserRequest) Reset() {
	*x = GetOrCreateUserRequest{}
	mi := &file_user_pkg_grpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateUserRequest) ProtoMessage() {}

func (x *GetOrCreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_pkg_grpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateUserRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_pkg_grpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_pkg_grpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_pkg_grpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_pkg_grpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_pkg_grpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_pkg_grpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_pkg_grpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_user_pkg_grpc_user_proto protoreflect.FileDescriptor

const file_user_pkg_grpc_user_proto_rawDesc = "" +
	"\n" +
	"\x18user/pkg/grpc/user.proto\x12\auser.v1\".\n" +
	"\x16GetOrCreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\x93\x01\n" +
	"\vUserService\x12I\n" +
	"\x0fGetOrCreateUser\x12\x1f.user.v1.GetOrCreateUserRequest\x1a\x15.user.v1.UserResponse\x129\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x15.user.v1.UserResponseB>Z<github.com/pure-golang/monorepo/backend/user/pkg/grpc;userpbb\x06proto3"

var (
	file_user_pkg_grpc_user_proto_rawDescOnce sync.Once
	file_user_pkg_grpc_user_proto_rawDescData []byte
)

func file_user_pkg_grpc_user_proto_rawDescGZIP() []byte {
	file_user_pkg_grpc_user_proto_rawDescOnce.Do(func() {
		file_user_pkg_grpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_pkg_grpc_user_proto_rawDesc), len(file_user_pkg_grpc_user_proto_rawDesc)))
	})
	return file_user_pkg_grpc_user_proto_rawDescData
}

var file_user_pkg_grpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_pkg_grpc_user_proto_goTypes = []any{
	(*GetOrCreateUserRequest)(nil), // 0: user.v1.GetOrCreateUserRequest
	(*GetUserRequest)(nil),         // 1: user.v1.GetUserRequest
	(*UserResponse)(nil),           // 2: user.v1.UserResponse
}
var file_user_pkg_grpc_user_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.GetOrCreateUser:input_type -> user.v1.GetOrCreateUserRequest
	1, // 1: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	2, // 2: user.v1.UserService.GetOrCreateUser:output_type -> user.v1.UserResponse
	2, // 3: user.v1.UserService.GetUser:output_type -> user.v1.UserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_pkg_grpc_user_proto_init() }
func file_user_pkg_grpc_user_proto_init() {
	if File_user_pkg_grpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_pkg_grpc_user_proto_rawDesc), len(file_user_pkg_grpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_pkg_grpc_user_proto_goTypes,
		DependencyIndexes: file_user_pkg_grpc_user_proto_depIdxs,
		MessageInfos:      file_user_pkg_grpc_user_proto_msgTypes,
	}.Build()
	File_user_pkg_grpc_user_proto = out.File
	file_user_pkg_grpc_user_proto_goTypes = nil
	file_user_pkg_grpc_user_proto_depIdxs = nil
}
