// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewCodeStore creates a new instance of CodeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeStore {
	mock := &CodeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CodeStore is an autogenerated mock type for the codeStore type
type CodeStore struct {
	mock.Mock
}

type CodeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeStore) EXPECT() *CodeStore_Expecter {
	return &CodeStore_Expecter{mock: &_m.Mock}
}

// DeleteCode provides a mock function for the type CodeStore
func (_mock *CodeStore) DeleteCode(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodeStore_DeleteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCode'
type CodeStore_DeleteCode_Call struct {
	*mock.Call
}

// DeleteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *CodeStore_Expecter) DeleteCode(ctx interface{}, email interface{}) *CodeStore_DeleteCode_Call {
	return &CodeStore_DeleteCode_Call{Call: _e.mock.On("DeleteCode", ctx, email)}
}

func (_c *CodeStore_DeleteCode_Call) Run(run func(ctx context.Context, email string)) *CodeStore_DeleteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeStore_DeleteCode_Call) Return(err error) *CodeStore_DeleteCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodeStore_DeleteCode_Call) RunAndReturn(run func(ctx context.Context, email string) error) *CodeStore_DeleteCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function for the type CodeStore
func (_mock *CodeStore) GetCode(ctx context.Context, email string) (string, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CodeStore_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type CodeStore_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *CodeStore_Expecter) GetCode(ctx interface{}, email interface{}) *CodeStore_GetCode_Call {
	return &CodeStore_GetCode_Call{Call: _e.mock.On("GetCode", ctx, email)}
}

func (_c *CodeStore_GetCode_Call) Run(run func(ctx context.Context, email string)) *CodeStore_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeStore_GetCode_Call) Return(s string, err error) *CodeStore_GetCode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CodeStore_GetCode_Call) RunAndReturn(run func(ctx context.Context, email string) (string, error)) *CodeStore_GetCode_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type CodeStore
func (_mock *CodeStore) IsTokenRevoked(ctx context.Context, tokenID string) (bool, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CodeStore_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type CodeStore_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *CodeStore_Expecter) IsTokenRevoked(ctx interface{}, tokenID interface{}) *CodeStore_IsTokenRevoked_Call {
	return &CodeStore_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, tokenID)}
}

func (_c *CodeStore_IsTokenRevoked_Call) Run(run func(ctx context.Context, tokenID string)) *CodeStore_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeStore_IsTokenRevoked_Call) Return(b bool, err error) *CodeStore_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CodeStore_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (bool, error)) *CodeStore_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type CodeStore
func (_mock *CodeStore) RevokeToken(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodeStore_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type CodeStore_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *CodeStore_Expecter) RevokeToken(ctx interface{}, tokenID interface{}) *CodeStore_RevokeToken_Call {
	return &CodeStore_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, tokenID)}
}

func (_c *CodeStore_RevokeToken_Call) Run(run func(ctx context.Context, tokenID string)) *CodeStore_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeStore_RevokeToken_Call) Return(err error) *CodeStore_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodeStore_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *CodeStore_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCode provides a mock function for the type CodeStore
func (_mock *CodeStore) SaveCode(ctx context.Context, email string, code string, ttl time.Duration) error {
	ret := _mock.Called(ctx, email, code, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, email, code, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodeStore_SaveCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCode'
type CodeStore_SaveCode_Call struct {
	*mock.Call
}

// SaveCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
//   - ttl time.Duration
func (_e *CodeStore_Expecter) SaveCode(ctx interface{}, email interface{}, code interface{}, ttl interface{}) *CodeStore_SaveCode_Call {
	return &CodeStore_SaveCode_Call{Call: _e.mock.On("SaveCode", ctx, email, code, ttl)}
}

func (_c *CodeStore_SaveCode_Call) Run(run func(ctx context.Context, email string, code string, ttl time.Duration)) *CodeStore_SaveCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CodeStore_SaveCode_Call) Return(err error) *CodeStore_SaveCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodeStore_SaveCode_Call) RunAndReturn(run func(ctx context.Context, email string, code string, ttl time.Duration) error) *CodeStore_SaveCode_Call {
	_c.Call.Return(run)
	return _c
}
