// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/monorepo/backend/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserClient is an autogenerated mock type for the userClient type
type UserClient struct {
	mock.Mock
}

type UserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserClient) EXPECT() *UserClient_Expecter {
	return &UserClient_Expecter{mock: &_m.Mock}
}

// GetOrCreateByEmail provides a mock function for the type UserClient
func (_mock *UserClient) GetOrCreateByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserClient_GetOrCreateByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateByEmail'
type UserClient_GetOrCreateByEmail_Call struct {
	*mock.Call
}

// GetOrCreateByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserClient_Expecter) GetOrCreateByEmail(ctx interface{}, email interface{}) *UserClient_GetOrCreateByEmail_Call {
	return &UserClient_GetOrCreateByEmail_Call{Call: _e.mock.On("GetOrCreateByEmail", ctx, email)}
}

func (_c *UserClient_GetOrCreateByEmail_Call) Run(run func(ctx context.Context, email string)) *UserClient_GetOrCreateByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_GetOrCreateByEmail_Call) Return(user *domain.User, err error) *UserClient_GetOrCreateByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserClient_GetOrCreateByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *UserClient_GetOrCreateByEmail_Call {
	_c.Call.Return(run)
	return _c
}
