template: testify
template-data:
  unroll-variadic: true
filename: "{{ .InterfaceName | snakecase }}.go"
dir: "{{ .InterfaceDir }}/mocks"
structname: "{{ .InterfaceName | firstUpper }}"
pkgname: mocks
packages:
  github.com/pure-golang/monorepo/backend/profile/internal/service:
    config:
      all: true
