// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/monorepo/backend/profile/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileRepo creates a new instance of ProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepo {
	mock := &ProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileRepo is an autogenerated mock type for the profileRepo type
type ProfileRepo struct {
	mock.Mock
}

type ProfileRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileRepo) EXPECT() *ProfileRepo_Expecter {
	return &ProfileRepo_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type ProfileRepo
func (_mock *ProfileRepo) GetByUserID(ctx context.Context, userID string) (*domain.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type ProfileRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ProfileRepo_Expecter) GetByUserID(ctx interface{}, userID interface{}) *ProfileRepo_GetByUserID_Call {
	return &ProfileRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *ProfileRepo_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *ProfileRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepo_GetByUserID_Call) Return(profile *domain.Profile, err error) *ProfileRepo_GetByUserID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *ProfileRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.Profile, error)) *ProfileRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IsNicknameTaken provides a mock function for the type ProfileRepo
func (_mock *ProfileRepo) IsNicknameTaken(ctx context.Context, nickname string) (bool, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for IsNicknameTaken")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileRepo_IsNicknameTaken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNicknameTaken'
type ProfileRepo_IsNicknameTaken_Call struct {
	*mock.Call
}

// IsNicknameTaken is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *ProfileRepo_Expecter) IsNicknameTaken(ctx interface{}, nickname interface{}) *ProfileRepo_IsNicknameTaken_Call {
	return &ProfileRepo_IsNicknameTaken_Call{Call: _e.mock.On("IsNicknameTaken", ctx, nickname)}
}

func (_c *ProfileRepo_IsNicknameTaken_Call) Run(run func(ctx context.Context, nickname string)) *ProfileRepo_IsNicknameTaken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileRepo_IsNicknameTaken_Call) Return(b bool, err error) *ProfileRepo_IsNicknameTaken_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ProfileRepo_IsNicknameTaken_Call) RunAndReturn(run func(ctx context.Context, nickname string) (bool, error)) *ProfileRepo_IsNicknameTaken_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNickname provides a mock function for the type ProfileRepo
func (_mock *ProfileRepo) UpsertNickname(ctx context.Context, userID string, nickname string) (*domain.Profile, error) {
	ret := _mock.Called(ctx, userID, nickname)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNickname")
	}

	var r0 *domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Profile, error)); ok {
		return returnFunc(ctx, userID, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Profile); ok {
		r0 = returnFunc(ctx, userID, nickname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileRepo_UpsertNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNickname'
type ProfileRepo_UpsertNickname_Call struct {
	*mock.Call
}

// UpsertNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - nickname string
func (_e *ProfileRepo_Expecter) UpsertNickname(ctx interface{}, userID interface{}, nickname interface{}) *ProfileRepo_UpsertNickname_Call {
	return &ProfileRepo_UpsertNickname_Call{Call: _e.mock.On("UpsertNickname", ctx, userID, nickname)}
}

func (_c *ProfileRepo_UpsertNickname_Call) Run(run func(ctx context.Context, userID string, nickname string)) *ProfileRepo_UpsertNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProfileRepo_UpsertNickname_Call) Return(profile *domain.Profile, err error) *ProfileRepo_UpsertNickname_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *ProfileRepo_UpsertNickname_Call) RunAndReturn(run func(ctx context.Context, userID string, nickname string) (*domain.Profile, error)) *ProfileRepo_UpsertNickname_Call {
	_c.Call.Return(run)
	return _c
}
