// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginPayload struct {
	Token  string `json:"token"`
	UserID string `json:"userID"`
	Email  string `json:"email"`
}

type LogoutPayload struct {
	Revoked bool `json:"revoked"`
}

type Mutation struct {
}

type Query struct {
}

type RequestEmailCodePayload struct {
	Accepted bool `json:"accepted"`
}
